$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:false,
    paginatiion:false,
    autoplay:1000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        800:{
            items:4
        },
        1000:{
            items:4
        }
    }
})

